# This is a basic workflow to help you get started with the Run Jtest action.
name: Scoped

on:
  # Trigger the workflow on push or pull request events but only for the master branch.
  push:
    branches: [ main, branch ]
  pull_request:
    branches: [ main, branch ]
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
  
jobs:
  build:
    name: Analyze project with Jtest with scope settings
    
    # Specifies the type of runner that the job will run on.
    runs-on: [self-hosted, arthas]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    # Runs code analysis with Jtest
    
    - name: Run Jtest
      working-directory: demo-project
      #id: jtest
      #run: D:/_JTest/parasoft_jtest_16.05/jtest/jtestcli.exe -config "builtin://Recommended Rules" -property report.format=xml,html,sarif -report "reports" -data demo.data.json
      #run: mvn clean jtest:jtest "-Djtest.config=builtin://Recommended Rules"
      run: C:/github/actions-runner/jtestRelV2022.1/jtestcli.exe -config "builtin://Recommended Rules" -report "reports" -data demo.data.json
      #uses: parasoft/run-jtest-action@0.0.2
      #with:
        #Uses the jtest.data.json generated with the Maven command in the previous step
       # input: demo-project/jtest.data.json
        
        # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: demo-project/reports/report.sarif # reports is a default location for reports directory

    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Static analysis reports
          path: demo-project/reports/*.*
