name: Java CI with Maven

on:
  workflow_dispatch: # allow to trigger the workflow manually
#   push:
#     branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
#   build-github-hosted:
#     name: Build project on github-hosted VM
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - name: Build with Maven
#       run: mvn -B package --file demo-project/pom.xml
  build-self-hosted:
    name: Build project on-premises
    runs-on: self-hosted # check array [self-hosted, windows, redish, x86] or redish only
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn -B package --file demo-project/pom.xml

      - name: Run Jtest with maven
        run: mvn clean --file demo-project/pom.xml test-compile jtest:agent test jtest:jtest -D'jtest.config'="builtin://Recommended Rules"

       #Archiving the findings reports as artifact
      - uses: actions/upload-artifact@v2
        with:
          name: Parasoft-Report
          path: |
            demo-project\target\jtest\report.html
            demo-project\target\jtest\report.xml

#      # Uploads the findings into the GitHub code scanning alert section using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: C:\Users\dszyszlak\Downloads\example_results.sarif #- TODO: PRODUCE JSON with SARIF FORMAT
